coverage:
  range: '60...100'
  precision: 2
  status:
    default:
      enabled: yes
      target: 90
      threshold: 1%
      if_not_found: success
      if_ci_failed: error
    patch:
      default:
        enabled: yes
        threshold: 0%
        if_not_found: success
        if_ci_failed: error

