name: Cypress E2E

on:
  schedule:
    - cron: '0 */2 * * *'
jobs:
  chrome-and-ff:
    name: E2E Chrome & FF
    timeout-minutes: 10
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
#        os: [ubuntu-16.04, ubuntu-latest] 파이어 폭스는 일단 제외
        os: [ubuntu-16.04]

    runs-on: ${{ matrix.os }}
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - if: matrix.os == 'ubuntu-16.04'
        name: Run E2E Chrome
        uses: cypress-io/github-action@v1
        with:
          browser: chrome

      - if: matrix.os == 'ubuntu-latest'
        name: Run E2E Firefox
        uses: cypress-io/github-action@v1
        with:
          browser: firefox

      - name: Upload Screenshot
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.os }}
          path: cypress/screenshots
          # Test run video was always captured, so this action uses "always()" condition
      - name: Upload Video
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos-${{ matrix.os }}
          path: cypress/videos
  edge:
    name: E2E Edge
    runs-on: windows-2019
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run E2E
        uses: cypress-io/github-action@v1
        with:
          browser: edge
          config-file: ''
          # cypress.json 을 못 찾아 임의로 설정해 둠

      - name: Upload Screenshot
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots-windows-2019
          path: cypress/screenshots
          # Test run video was always captured, so this action uses "always()" condition
      - name: Upload Video
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos-windows-2019
          path: cypress/videos
