name: Cypress E2E

on:
  push:
    branches:
      - cypress-ts
#  schedule:
#    - cron: '0 */1 * * *'

jobs:
  e2e:
    name: Cypress E2E
    runs-on: ubuntu-16.04
    container: cypress/browsers:node12.13.0-chrome78-ff70
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Cypress
        uses: cypress-io/github-action@v1
        with:
          browser: chrome

