name: Cypress E2E Firefox

on:
  push:
    branches:
      - cypress-ts
#  schedule:
#    - cron: '0 */1 * * *'

jobs:
  e2e:
    name: Cypress E2E Firefox
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Cypress
        uses: cypress-io/github-action@v1
        with:
          browser: firefox

      - name: Upload Screenshot
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots-firefox
          path: cypress/screenshots
          # Test run video was always captured, so this action uses "always()" condition
      - name: Upload Video
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos-firefox
          path: cypress/videos
